---
title: "Applied Data Mining Homework 2"
author: "Xun Zhao, xz2827"
output: pdf_document
fontsize: 12pt
---

# 1. Classifier $g_m$

```{r}
train_g = function(m, data){
    vectors = data[-ncol(data)]
    labels = ifelse(data[,ncol(data)] == data[1,ncol(data)], 1, -1)

    pairs = sapply(1:m, function(i){
        x.pos = vectors[sample(row.names(vectors[labels == 1,]), 1),]
        x.neg = vectors[sample(row.names(vectors[labels == -1,]), 1),]

        w = (x.pos - x.neg) / sum((x.pos - x.neg) ^ 2)
        c.w = sum(w * (x.pos + x.neg) / 2)

        misc = sum(sign(as.matrix(w) %*% t(as.matrix(vectors)) - c.w) != labels)
        s = ifelse(misc < nrow(data) / 2, 1, -1)

        v = s * w
        c = sum(v * (x.pos + x.neg) / 2)

        return(c(as.matrix(v), c))
    })
    return(list(t(pairs[1:ncol(vectors),]), as.matrix(pairs[nrow(pairs),])))
}
```

# Classifier Function 


`V` and `c` is the result of function $g_m$.

```{r}
classify = function(x, V, c){
    return(sign(sum(sign(V %*% as.matrix(x) - c))))
}
```

# Load Data from `wdbcdata.zip`

Shuffle the data and separate it into two parts with equal size.

```{r}
data.d = read.csv('../Data/wdbc.data')
data.l = read.csv('../Data/wdbc.labels')
data = data.frame(data.d, data.l)
data = data[sample(1:nrow(data)),]
data.tr = data[1:round(nrow(data) / 2),]
data.ts = data[(round(nrow(data) / 2) + 1):nrow(data),]
```

# Train with Different $m$

```{r}
m.seq = seq(1, 3, 2)
err.rates = sapply(
    m.seq, 
    function(m){
        Vc = train_g(m, data.tr)
        V = Vc[[1]]
        c = Vc[[2]]
        esti = apply(
            t(as.matrix(data.ts[,-ncol(data.ts)])), 2, 
            classify, V = V, c = c
            )
        err.rate = sum(esti != data.ts[,ncol(data.ts)]) / nrow(data.ts)
        return(err.rate)
        }
    )
library(ggplot2)
graph = ggplot(
    data.frame(cbind(m.seq, err.rates)), 
    aes(x = m.seq, y = err.rates)
    ) + 
    geom_point()
plot(graph)
```