w1 = c(1, 1)
w2 = c(1, 1 / 2)
w3 = c(1, -1)
w4 = c(1, -1 / 2)
X = seq(-10, 10, length.out = 101)
sigmoid = function(x) as.matrix(1 / (1 + exp(-x)))
max0 = function(x) as.matrix(ifelse(x > 0, x, 0))
f = function(X, W, phi){
	W = t(as.matrix(W))
	X = as.matrix(X)
	W2 = as.matrix(c(1, 1))
	Z = phi(X %*% W)
	Y_ = sigmoid(Z %*% W2)
}
Ws = rbind(w1, w2, w3, w4)
par(mfrow = c(2, 2))
apply(Ws, 1, FUN = function(w)plot(X, f(X, w, sigmoid), type = 'l'))
par(mfrow = c(2, 2))
apply(Ws, 1, FUN = function(w)plot(X, f(X, w, max0), type = 'l'))